### ISSUE TITLE
expandHelperAssetsFileReferenceArray silently chokes on invalid YAML files

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levure#106] opened 2018-10-11 22:27 UTC
If a helper has an invalid helper.yml file,  loadHelperConfigurationFile returns "Invalid YAML File", but then expandHelperAssetsFileReferenceArray doesn't do anything with that information.  It just skips the helper and moves on to the next one.  The result is that the helper doesn't load, but no error is thrown.

**Comment by trevordevore** [comment] 2018-10-12 17:02
@macMikey Can you try the PR I've submitted and see if it sufficiently addresses this issue?

**Comment by macMikey** [comment] 2018-10-12 20:41
No, see the notes on the PR.

**Comment by macMikey** [comment] 2018-10-12 20:57
OK, latest PR fixes it.  Suggestion:  the yaml parser can be more hepful than "invalid yaml file".  There are several types of failures that the parser detects.

**Comment by trevordevore** [comment] 2018-10-12 20:59
That sounds like a great PR for you to submit ;-)

**Comment by macMikey** [comment] 2018-10-12 21:02
ok, leave the issue open, and i'll work on it this weekend.  I was thinking about this last night when I was expletive-deep in the framework chasing this.

**Comment by trevordevore** [comment] 2018-10-12 21:03
I'm going to close this issue as the issue is fixed. Better YAML error reporting should be handled under a different issue.

**Closed by trevordevore** 2018-10-12 21:03 UTC
